# Site settings
title: "History Walker Blog"
email: "your-email@example.com"
description: "A blog about history and exploration"
baseurl: ""
url: "https://historywalker.com"
twitter_username: ""
github_username: "robertreppel"

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Minimal Mistakes theme settings
minimal_mistakes_skin: "default"